Fix vertical nav bar issue #27
dailydotdev/daily-apps pull request #202
Opened 2020-10-26 18:00 UTC by saqibameen

Provides a fix for the #27

2020-10-26 20:01 UTC, saqibameen commented
> Actually `updateLines` is called upon any change to the `posts` object in the store. You don't have to actually call `fetchNextFeedPage` but rather add more posts. Once the `posts` object changes the `updateLines` will be called.

_Originally posted by @idoshamun in https://github.com/dailydotdev/daily-apps/issues/27#issuecomment-607177560_

Following on our conversation on the issue page. Here's what I wrote in the test: 

```js
  const wrapper = mount(DaHome, { store, localVue });

// 1 [] - no post

  feed.state.posts = [...POSTS_DUMMY_DATA, ...POSTS_DUMMY_DATA, ...POSTS_DUMMY_DATA, ...POSTS_DUMMY_DATA, ...POSTS_DUMMY_DATA, ...POSTS_DUMMY_DATA, ...POSTS_DUMMY_DATA, ...POSTS_DUMMY_DATA, ...POSTS_DUMMY_DATA];

  console.log(wrapper.vm.lineNumbers, wrapper.vm.posts); // 1 [ // all posts]
```

I see that posts are added but the lineNumbers isn't updating. While it is working fine for me in the browser. I am not sure what I'm doing wrong here. 

Ignore console.log, posts population, I am just trying to get it working here. Will update after that.

2020-10-27 16:05 UTC, idoshamun requested changes
Thanks for your contribution!
I'm not sure exactly what is the fix as currently, I can see only one change.
Did you forget by any chance to push some commits?

2020-10-27 17:28 UTC, saqibameen commented on packages/components/package.json
> +    "vue-context": "^4.1.1",
They were probably auto bumped up. I didn't do it manually. Reverted.

2020-10-27 17:39 UTC, saqibameen commented
> Thanks for your contribution!
> I'm not sure exactly what is the fix as currently, I can see only one change.
> Did you forget by any chance to push some commits?

The `Home.vue` was watching for `posts` to call `updateLines()` but `posts` was not imported from store into `Home.vue`. That was the only issue. My guess is probably during the refactoring/updates, `posts` variable was moved to DaFeed and removed from Home.vue. Adding it fixes the issue.

2020-10-27 19:19 UTC, idoshamun commented
Oh, this is perfect! Thanks for the explanation.
So should we wait for the test then? You might need to call `$nextTick` after changing the posts variable.

2020-10-27 19:28 UTC, saqibameen commented
> Oh, this is perfect! Thanks for the explanation.
> So should we wait for the test then? You might need to call `$nextTick` after changing the posts variable.

Yeah, trying to figure out the test part. Might learn a thing or two about testing and make it future proof. 

I tried calling `$nextTick` once. Didn't change anything.

2020-11-18 08:56 UTC, idoshamun commented
Hey @saqibameen,

Can I assist in any way so we can proceed with this PR?

2020-11-26 10:18 UTC, idoshamun commented
I'm closing this issue as we redesign the sidebar, so this is no longer relevant.
Thanks for the efforts so far.

2020-11-26 10:18 UTC, closed without merging